### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-template-generator#2]
主機能:

-   [ ] 主にサンプルを用いた単純な型の認識
-   [ ] パターンマッチによる YES / NO 文字列の解析
-   [ ] パターンマッチによる MOD の解析
-   [ ] サンプルを用いた出力フォーマットの推論
-   [ ] 自然言語解析による変数の制約の解析
-   [ ] 自然言語解析による変数の意味 (グラフかどうかなど) の解析
-   [ ] 自然言語解析による入力フォーマットの解析

その他:

-   [ ] PyPI への登録
-   [ ] 品質が安定してきたら宣伝をする
-   [ ] デフォルトのテンプレートを増やす
-   [ ] 外部向けインターフェースの安定化
-   [ ] テストを書く
-   [ ] ドキュメントを書く

**Comment by kmyk** [comment]
PyPI 登録した。GitHub Release を作ったら反映されるいつものやつの設定もした

**Comment by kmyk** [comment]
- サンプルを利用したフォーマット推測を入れたのでこどふぉでも動くようになった
- きゅうりさんに感謝しつつ定数解析をした
- 出力パートの改善をした

**Comment by kmyk** [comment]
- [ ] 入力フォーマットと出力サンプルを組み合わせての出力フォーマット解析

**Comment by kmyk** [comment]
とりあえず基本機能は動くようになったので oj のラッパーに提案をしてきた https://github.com/kjnh10/pcm/issues/36 https://github.com/Tatamo/atcoder-cli/issues/25
これも online-judge-tools と同様にミドルウェアぐらいの位置に収めていきたい

**Comment by kmyk** [comment]
- [ ] とりあえず足した `template.py` の中身を埋める

**Comment by kmyk** [comment]
- [ ] `oj-prepare` が自動で最大ケースや最小ケースも生成して `test/` に追加しておいてくれるようにする

**Comment by kmyk** [comment]
- [ ] いま `*/generator/_cplusplus.py` にある出力の最適化を analyzer 側へ移送し、Python などからも利用できるように
- [ ] `*/generator/__init__.py` や `*/analyzer/combined.py` にある種の entry points があるが、これを明確にするために `main.py` みたいな名前にする
- [ ] `main.py` でも定数の宣言や出力の最適化をする
- [ ] `generator.cpp` みたいなのを作る #5

**Comment by kmyk** [comment]
- [ ] 生成結果の banner に version 情報を埋め込み

**Comment by kmyk** [comment]
- [ ] そろそろリファクタリングしないとしんどい

**Comment by kmyk** [comment]
- [ ] `oj-template -t topcoder.cpp` の指定なしで Topcoder をいい感じにしてくれ
- [ ] Topcoder の `int` と `long` の区別を忘れてないか？ そもそも `long` ってあったっけ？

**Comment by kmyk** [comment]
- [ ] Topcoder 用の `main` 関数の中の `solve` を修正する

**Comment by kmyk** [comment]
- [ ] `main.cpp` が汚いのでなんとかする
